### ISSUE TITLE
Command Line Util `soul play` not closing soul process

### ISSUE THREAD

**Issue by eaeiv** [soul-lang/SOUL#18] opened 2020-01-19 02:50 UTC
Windows x64 10.0.17763 Build 17763
Scarlett 2i2
SOUL master branch
Command Line Utils v0.8.875

I just pulled the repo's master branch and installed 0.8.875 of the command line tools to mess around with the standalone example .soul files. When using `soul play [soul file]` the first time, the program spawns a soul process, outputs execution info to my terminal, and outputs the audio. ***However, the soul process never closes***. Running another `soul play` command yields another spawned soul process, command line output, but no audio. By repeating this you can spawn keep spawning new soul processes that will never close or output any audio. 

Killing all of the soul processes fixes the audio issue allowing the `soul play` command to output audio, but the process still has to be killed manually.

Can anyone else replicate this issue?

**Comment by cesaref** [comment] 2020-01-19 16:25
That's an odd one - i take it you mean playing a soul file, not a soulpatch? I'll try and replicate this

**Comment by cesaref** [comment] 2020-01-27 11:13
I've reproduced this behaviour on windows. The issue I think is to do with how the Projucer project is configured, so i'm going to investigate what can be done. If you launch a soulpatch, you end up with a GUI window for the soul process, so closing it is much easier! Also, if you run it under cygwin it behaves how you'd probably expect (the command prompt doesn't return and you can control-c the running process).

The problem with only the first running soul.exe giving audio output is due to an exclusive opening of the audio driver if it's available. This gives the best performance, but is clearly something that you may not want so I think it's best if we add support for exclusive access as a command line option (not the default).

**Comment by cesaref** [comment] 2020-04-05 07:07
I believe this is fixed in the current version

**Closed by cesaref** 2020-04-05 07:07 UTC
